spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    # giới hạn toàn bộ request (phải >= tổng các file)   # giới hạn toàn bộ request (phải >= tổng các file)
jwt:
  secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS"
  expMinutes: 60